/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_checkbox = 1,
  sym_checkmark = 2,
  sym_cancelled_mark = 3,
  aux_sym_statement_token1 = 4,
  sym__category_expression = 5,
  sym__comment_identifier = 6,
  sym_source_file = 7,
  sym__definition = 8,
  sym_category = 9,
  sym_task = 10,
  sym_statement = 11,
  sym__category_definition = 12,
  sym_todo = 13,
  sym_done = 14,
  sym_cancelled = 15,
  sym_comment = 16,
  aux_sym_source_file_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_checkbox] = "checkbox",
  [sym_checkmark] = "checkmark",
  [sym_cancelled_mark] = "cancelled_mark",
  [aux_sym_statement_token1] = "statement_token1",
  [sym__category_expression] = "_category_expression",
  [sym__comment_identifier] = "_comment_identifier",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_category] = "category",
  [sym_task] = "task",
  [sym_statement] = "statement",
  [sym__category_definition] = "_category_definition",
  [sym_todo] = "todo",
  [sym_done] = "done",
  [sym_cancelled] = "cancelled",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_checkbox] = sym_checkbox,
  [sym_checkmark] = sym_checkmark,
  [sym_cancelled_mark] = sym_cancelled_mark,
  [aux_sym_statement_token1] = aux_sym_statement_token1,
  [sym__category_expression] = sym__category_expression,
  [sym__comment_identifier] = sym__comment_identifier,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_category] = sym_category,
  [sym_task] = sym_task,
  [sym_statement] = sym_statement,
  [sym__category_definition] = sym__category_definition,
  [sym_todo] = sym_todo,
  [sym_done] = sym_done,
  [sym_cancelled] = sym_cancelled,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_checkbox] = {
    .visible = true,
    .named = true,
  },
  [sym_checkmark] = {
    .visible = true,
    .named = true,
  },
  [sym_cancelled_mark] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_statement_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__category_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_category] = {
    .visible = true,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__category_definition] = {
    .visible = false,
    .named = true,
  },
  [sym_todo] = {
    .visible = true,
    .named = true,
  },
  [sym_done] = {
    .visible = true,
    .named = true,
  },
  [sym_cancelled] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == 0x2610) ADVANCE(5);
      if (lookahead == 0x2612) ADVANCE(7);
      if (lookahead == 0x2714) ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == 0x2610) ADVANCE(5);
      if (lookahead == 0x2612) ADVANCE(7);
      if (lookahead == 0x2714) ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_checkbox);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_checkmark);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_cancelled_mark);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_statement_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_statement_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym__category_expression);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__comment_identifier);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_checkbox] = ACTIONS(1),
    [sym_checkmark] = ACTIONS(1),
    [sym_cancelled_mark] = ACTIONS(1),
    [sym__category_expression] = ACTIONS(1),
    [sym__comment_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym__definition] = STATE(2),
    [sym_category] = STATE(2),
    [sym_task] = STATE(2),
    [sym__category_definition] = STATE(4),
    [sym_todo] = STATE(5),
    [sym_done] = STATE(5),
    [sym_cancelled] = STATE(5),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_checkbox] = ACTIONS(5),
    [sym_checkmark] = ACTIONS(7),
    [sym_cancelled_mark] = ACTIONS(9),
    [sym__category_expression] = ACTIONS(11),
    [sym__comment_identifier] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__definition] = STATE(3),
    [sym_category] = STATE(3),
    [sym_task] = STATE(3),
    [sym__category_definition] = STATE(4),
    [sym_todo] = STATE(5),
    [sym_done] = STATE(5),
    [sym_cancelled] = STATE(5),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_checkbox] = ACTIONS(5),
    [sym_checkmark] = ACTIONS(7),
    [sym_cancelled_mark] = ACTIONS(9),
    [sym__category_expression] = ACTIONS(11),
    [sym__comment_identifier] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__definition] = STATE(3),
    [sym_category] = STATE(3),
    [sym_task] = STATE(3),
    [sym__category_definition] = STATE(4),
    [sym_todo] = STATE(5),
    [sym_done] = STATE(5),
    [sym_cancelled] = STATE(5),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_checkbox] = ACTIONS(19),
    [sym_checkmark] = ACTIONS(22),
    [sym_cancelled_mark] = ACTIONS(25),
    [sym__category_expression] = ACTIONS(28),
    [sym__comment_identifier] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(34), 2,
      ts_builtin_sym_end,
      sym__category_expression,
    ACTIONS(36), 4,
      sym_checkbox,
      sym_checkmark,
      sym_cancelled_mark,
      sym__comment_identifier,
  [11] = 2,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      sym__category_expression,
    ACTIONS(40), 4,
      sym_checkbox,
      sym_checkmark,
      sym_cancelled_mark,
      sym__comment_identifier,
  [22] = 2,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      sym__category_expression,
    ACTIONS(44), 4,
      sym_checkbox,
      sym_checkmark,
      sym_cancelled_mark,
      sym__comment_identifier,
  [33] = 2,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      sym__category_expression,
    ACTIONS(48), 4,
      sym_checkbox,
      sym_checkmark,
      sym_cancelled_mark,
      sym__comment_identifier,
  [44] = 2,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      sym__category_expression,
    ACTIONS(52), 4,
      sym_checkbox,
      sym_checkmark,
      sym_cancelled_mark,
      sym__comment_identifier,
  [55] = 2,
    ACTIONS(54), 2,
      ts_builtin_sym_end,
      sym__category_expression,
    ACTIONS(56), 4,
      sym_checkbox,
      sym_checkmark,
      sym_cancelled_mark,
      sym__comment_identifier,
  [66] = 2,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      sym__category_expression,
    ACTIONS(60), 4,
      sym_checkbox,
      sym_checkmark,
      sym_cancelled_mark,
      sym__comment_identifier,
  [77] = 2,
    ACTIONS(62), 1,
      aux_sym_statement_token1,
    STATE(7), 1,
      sym_statement,
  [84] = 2,
    ACTIONS(62), 1,
      aux_sym_statement_token1,
    STATE(8), 1,
      sym_statement,
  [91] = 2,
    ACTIONS(62), 1,
      aux_sym_statement_token1,
    STATE(9), 1,
      sym_statement,
  [98] = 1,
    ACTIONS(64), 1,
      aux_sym_statement_token1,
  [102] = 1,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 11,
  [SMALL_STATE(6)] = 22,
  [SMALL_STATE(7)] = 33,
  [SMALL_STATE(8)] = 44,
  [SMALL_STATE(9)] = 55,
  [SMALL_STATE(10)] = 66,
  [SMALL_STATE(11)] = 77,
  [SMALL_STATE(12)] = 84,
  [SMALL_STATE(13)] = 91,
  [SMALL_STATE(14)] = 98,
  [SMALL_STATE(15)] = 102,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_category, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_category, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_todo, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_todo, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_done, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_done, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cancelled, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cancelled, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [66] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_todofiles(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "todofiles",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
