/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 20
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_done_tag = 1,
  sym_cancelled_tag = 2,
  sym_category_expression = 3,
  sym_todo_expression = 4,
  sym_done_expression = 5,
  sym_cancelled_expression = 6,
  sym_comment_expression = 7,
  sym_source_file = 8,
  sym__definition = 9,
  sym__category = 10,
  sym_task = 11,
  sym_comment = 12,
  sym_data = 13,
  sym_category_definition = 14,
  sym_todo_definition = 15,
  sym_done_definition = 16,
  sym_cancelled_definition = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym__category_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_done_tag] = "done_tag",
  [sym_cancelled_tag] = "cancelled_tag",
  [sym_category_expression] = "category_expression",
  [sym_todo_expression] = "todo_expression",
  [sym_done_expression] = "done_expression",
  [sym_cancelled_expression] = "cancelled_expression",
  [sym_comment_expression] = "comment_expression",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__category] = "_category",
  [sym_task] = "task",
  [sym_comment] = "comment",
  [sym_data] = "data",
  [sym_category_definition] = "category_definition",
  [sym_todo_definition] = "todo_definition",
  [sym_done_definition] = "done_definition",
  [sym_cancelled_definition] = "cancelled_definition",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__category_repeat1] = "_category_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_done_tag] = sym_done_tag,
  [sym_cancelled_tag] = sym_cancelled_tag,
  [sym_category_expression] = sym_category_expression,
  [sym_todo_expression] = sym_todo_expression,
  [sym_done_expression] = sym_done_expression,
  [sym_cancelled_expression] = sym_cancelled_expression,
  [sym_comment_expression] = sym_comment_expression,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__category] = sym__category,
  [sym_task] = sym_task,
  [sym_comment] = sym_comment,
  [sym_data] = sym_data,
  [sym_category_definition] = sym_category_definition,
  [sym_todo_definition] = sym_todo_definition,
  [sym_done_definition] = sym_done_definition,
  [sym_cancelled_definition] = sym_cancelled_definition,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__category_repeat1] = aux_sym__category_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_done_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_cancelled_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_category_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_done_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_cancelled_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__category] = {
    .visible = false,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_data] = {
    .visible = true,
    .named = true,
  },
  [sym_category_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_done_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_cancelled_definition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__category_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == '@') ADVANCE(8);
      if (lookahead == 0x2610) ADVANCE(4);
      if (lookahead == 0x2612) ADVANCE(5);
      if (lookahead == 0x2714) ADVANCE(6);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == '@') ADVANCE(8);
      if (lookahead == 0x2610) ADVANCE(4);
      if (lookahead == 0x2612) ADVANCE(5);
      if (lookahead == 0x2714) ADVANCE(6);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 0x2610) ADVANCE(4);
      if (lookahead == 0x2612) ADVANCE(5);
      if (lookahead == 0x2714) ADVANCE(6);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(47);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(44);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(45);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'c') ADVANCE(7);
      if (lookahead == 'd') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'c') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'd') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'e') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'e') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'l') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'l') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'n') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'n') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'o') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == '@') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(21);
      if (lookahead == 'd') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 32:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 33:
      if (eof) ADVANCE(34);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == '\n') SKIP(33);
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 0x2610) ADVANCE(4);
      if (lookahead == 0x2612) ADVANCE(5);
      if (lookahead == 0x2714) ADVANCE(6);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_done_tag);
      if (lookahead == ':') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_done_tag);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_cancelled_tag);
      if (lookahead == ':') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_cancelled_tag);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_category_expression);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_category_expression);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(47);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_category_expression);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_category_expression);
      if (lookahead == ':') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_category_expression);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_todo_expression);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_done_expression);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_cancelled_expression);
      if (lookahead == ':') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_comment_expression);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 33},
  [2] = {.lex_state = 33},
  [3] = {.lex_state = 33},
  [4] = {.lex_state = 33},
  [5] = {.lex_state = 33},
  [6] = {.lex_state = 33},
  [7] = {.lex_state = 33},
  [8] = {.lex_state = 33},
  [9] = {.lex_state = 33},
  [10] = {.lex_state = 33},
  [11] = {.lex_state = 33},
  [12] = {.lex_state = 33},
  [13] = {.lex_state = 33},
  [14] = {.lex_state = 33},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 20},
  [17] = {.lex_state = 20},
  [18] = {.lex_state = 20},
  [19] = {.lex_state = 20},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_done_tag] = ACTIONS(1),
    [sym_cancelled_tag] = ACTIONS(1),
    [sym_category_expression] = ACTIONS(1),
    [sym_todo_expression] = ACTIONS(1),
    [sym_done_expression] = ACTIONS(1),
    [sym_cancelled_expression] = ACTIONS(1),
    [sym_comment_expression] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym__definition] = STATE(8),
    [sym__category] = STATE(8),
    [sym_category_definition] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_category_expression] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__category] = STATE(3),
    [sym_task] = STATE(11),
    [sym_comment] = STATE(11),
    [sym_data] = STATE(3),
    [sym_category_definition] = STATE(5),
    [sym_todo_definition] = STATE(12),
    [sym_done_definition] = STATE(18),
    [sym_cancelled_definition] = STATE(19),
    [aux_sym__category_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_category_expression] = ACTIONS(9),
    [sym_todo_expression] = ACTIONS(12),
    [sym_done_expression] = ACTIONS(14),
    [sym_cancelled_expression] = ACTIONS(16),
    [sym_comment_expression] = ACTIONS(18),
  },
  [STATE(3)] = {
    [sym__category] = STATE(4),
    [sym_task] = STATE(11),
    [sym_comment] = STATE(11),
    [sym_data] = STATE(4),
    [sym_category_definition] = STATE(5),
    [sym_todo_definition] = STATE(12),
    [sym_done_definition] = STATE(18),
    [sym_cancelled_definition] = STATE(19),
    [aux_sym__category_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(20),
    [sym_category_expression] = ACTIONS(22),
    [sym_todo_expression] = ACTIONS(12),
    [sym_done_expression] = ACTIONS(14),
    [sym_cancelled_expression] = ACTIONS(16),
    [sym_comment_expression] = ACTIONS(18),
  },
  [STATE(4)] = {
    [sym__category] = STATE(4),
    [sym_task] = STATE(11),
    [sym_comment] = STATE(11),
    [sym_data] = STATE(4),
    [sym_category_definition] = STATE(5),
    [sym_todo_definition] = STATE(12),
    [sym_done_definition] = STATE(18),
    [sym_cancelled_definition] = STATE(19),
    [aux_sym__category_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_category_expression] = ACTIONS(27),
    [sym_todo_expression] = ACTIONS(30),
    [sym_done_expression] = ACTIONS(33),
    [sym_cancelled_expression] = ACTIONS(36),
    [sym_comment_expression] = ACTIONS(39),
  },
  [STATE(5)] = {
    [sym__category] = STATE(6),
    [sym_task] = STATE(11),
    [sym_comment] = STATE(11),
    [sym_data] = STATE(6),
    [sym_category_definition] = STATE(5),
    [sym_todo_definition] = STATE(12),
    [sym_done_definition] = STATE(18),
    [sym_cancelled_definition] = STATE(19),
    [aux_sym__category_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_category_expression] = ACTIONS(9),
    [sym_todo_expression] = ACTIONS(42),
    [sym_done_expression] = ACTIONS(45),
    [sym_cancelled_expression] = ACTIONS(48),
    [sym_comment_expression] = ACTIONS(51),
  },
  [STATE(6)] = {
    [sym__category] = STATE(4),
    [sym_task] = STATE(11),
    [sym_comment] = STATE(11),
    [sym_data] = STATE(4),
    [sym_category_definition] = STATE(5),
    [sym_todo_definition] = STATE(12),
    [sym_done_definition] = STATE(18),
    [sym_cancelled_definition] = STATE(19),
    [aux_sym__category_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(20),
    [sym_category_expression] = ACTIONS(22),
    [sym_todo_expression] = ACTIONS(54),
    [sym_done_expression] = ACTIONS(57),
    [sym_cancelled_expression] = ACTIONS(60),
    [sym_comment_expression] = ACTIONS(63),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      sym_category_expression,
    ACTIONS(68), 4,
      sym_todo_expression,
      sym_done_expression,
      sym_cancelled_expression,
      sym_comment_expression,
  [11] = 4,
    ACTIONS(5), 1,
      sym_category_expression,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_category_definition,
    STATE(13), 3,
      sym__definition,
      sym__category,
      aux_sym_source_file_repeat1,
  [26] = 2,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      sym_category_expression,
    ACTIONS(74), 4,
      sym_todo_expression,
      sym_done_expression,
      sym_cancelled_expression,
      sym_comment_expression,
  [37] = 2,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      sym_category_expression,
    ACTIONS(78), 4,
      sym_todo_expression,
      sym_done_expression,
      sym_cancelled_expression,
      sym_comment_expression,
  [48] = 2,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_category_expression,
    ACTIONS(82), 4,
      sym_todo_expression,
      sym_done_expression,
      sym_cancelled_expression,
      sym_comment_expression,
  [59] = 2,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      sym_category_expression,
    ACTIONS(86), 4,
      sym_todo_expression,
      sym_done_expression,
      sym_cancelled_expression,
      sym_comment_expression,
  [70] = 4,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 1,
      sym_category_expression,
    STATE(2), 1,
      sym_category_definition,
    STATE(13), 3,
      sym__definition,
      sym__category,
      aux_sym_source_file_repeat1,
  [85] = 2,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      sym_category_expression,
    ACTIONS(95), 4,
      sym_todo_expression,
      sym_done_expression,
      sym_cancelled_expression,
      sym_comment_expression,
  [96] = 1,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
  [100] = 1,
    ACTIONS(99), 1,
      sym_done_tag,
  [104] = 1,
    ACTIONS(101), 1,
      sym_cancelled_tag,
  [108] = 1,
    ACTIONS(103), 1,
      sym_done_tag,
  [112] = 1,
    ACTIONS(103), 1,
      sym_cancelled_tag,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 11,
  [SMALL_STATE(9)] = 26,
  [SMALL_STATE(10)] = 37,
  [SMALL_STATE(11)] = 48,
  [SMALL_STATE(12)] = 59,
  [SMALL_STATE(13)] = 70,
  [SMALL_STATE(14)] = 85,
  [SMALL_STATE(15)] = 96,
  [SMALL_STATE(16)] = 100,
  [SMALL_STATE(17)] = 104,
  [SMALL_STATE(18)] = 108,
  [SMALL_STATE(19)] = 112,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__category, 1, 0, 0),
  [9] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__category, 1, 0, 0), SHIFT(7),
  [12] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [14] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [16] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [18] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__category, 2, 0, 0),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__category, 2, 0, 0), SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__category_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__category_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__category_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__category_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__category_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__category_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__category, 1, 0, 0), SHIFT(9),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__category, 1, 0, 0), SHIFT(16),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__category, 1, 0, 0), SHIFT(17),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__category, 1, 0, 0), SHIFT(10),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__category, 2, 0, 0), SHIFT(9),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__category, 2, 0, 0), SHIFT(16),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__category, 2, 0, 0), SHIFT(17),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__category, 2, 0, 0), SHIFT(10),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_category_definition, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_category_definition, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_todo_definition, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_todo_definition, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_done_definition, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cancelled_definition, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_todofiles(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "todofiles",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
